services:
  # Backend API Service
  - type: web
    name: quantinsight-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: quantinsight-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: quantinsight-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FINNHUB_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        value: https://quantinsight-ai.vercel.app
      - key: CORS_ORIGINS
        value: https://quantinsight-ai.vercel.app,https://localhost:3000
    healthCheckPath: /health
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: quantinsight-db
    plan: free
    databaseName: quantinsight
    user: quantinsight

services:
  # Redis Cache (Optional - comment out if not needed)
  - type: redis
    name: quantinsight-redis
    plan: free
    ipAllowList: []